language: python
python:
  - 2.7
addons:
  apt:
    packages:
      - libhdf5-serial-dev
env:
  global:
      - PIP_INDEX_URL=https://pypi.pacificclimate.org/simple
install:
  - pip install -r requirements.txt
  - pip install .
script: 
  - py.test
