language: python
python:
  - 2.7
install:
  - pip install -i http://tools.pacificclimate.org/pypiserver/ -r requirements.txt
  - pip install -i http://tools.pacificclimate.org/pypiserver/ .
script: 
  - py.test
